// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVeLeidEWd4vCOXTXUHq2YCpI9Fd72xM',
    appId: '1:448883504279:web:a4486605a4e72672d6e5d2',
    messagingSenderId: '448883504279',
    projectId: 'najali-chaimae-tp-ai2',
    authDomain: 'najali-chaimae-tp-ai2.firebaseapp.com',
    storageBucket: 'najali-chaimae-tp-ai2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO9zRPZ2GddW9MVTBg6c7rXruFwsH2Q6A',
    appId: '1:448883504279:android:6878daf78b784b35d6e5d2',
    messagingSenderId: '448883504279',
    projectId: 'najali-chaimae-tp-ai2',
    storageBucket: 'najali-chaimae-tp-ai2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvLZKRcklSWamP4Xrwbir0UdiCPm5Cco',
    appId: '1:448883504279:ios:391ee81d23b65ef2d6e5d2',
    messagingSenderId: '448883504279',
    projectId: 'najali-chaimae-tp-ai2',
    storageBucket: 'najali-chaimae-tp-ai2.appspot.com',
    iosBundleId: 'com.example.najalichaimaetpai2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvLZKRcklSWamP4Xrwbir0UdiCPm5Cco',
    appId: '1:448883504279:ios:8cb78cd195213263d6e5d2',
    messagingSenderId: '448883504279',
    projectId: 'najali-chaimae-tp-ai2',
    storageBucket: 'najali-chaimae-tp-ai2.appspot.com',
    iosBundleId: 'com.example.najalichaimaetpai2.RunnerTests',
  );
}
